#!/usr/bin/env node
/**
 * Generate Pattern Types Script
 *
 * Extracts all pattern type names from patterns-registry.json and generates
 * a TypeScript file with a PatternType union type for compile-time validation.
 *
 * Usage: npx tsx scripts/generate-pattern-types.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface PatternsRegistry {
    version: string;
    exportedAt: string;
    patterns: Record<string, unknown>;
}

async function main() {
    const registryPath = path.join(__dirname, '../src/patterns-registry.json');
    const outputPath = path.join(__dirname, '../src/pattern-types.ts');

    console.log('Reading patterns registry...');
    const registryContent = fs.readFileSync(registryPath, 'utf-8');
    const registry: PatternsRegistry = JSON.parse(registryContent);

    const patternNames = Object.keys(registry.patterns).sort();
    console.log(`Found ${patternNames.length} patterns`);

    // Generate TypeScript file
    const tsContent = `/**
 * Pattern Types (Auto-Generated)
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-pattern-types.ts
 * Run: npx tsx scripts/generate-pattern-types.ts
 *
 * Generated: ${new Date().toISOString()}
 * Pattern count: ${patternNames.length}
 */

/**
 * All valid pattern type names from almadar-patterns registry.
 * Use this type in render-ui effects for compile-time validation.
 *
 * @example
 * const pattern: PatternConfig = {
 *   type: 'entity-table', // ✅ Valid
 *   entity: 'Task',
 * };
 *
 * const invalid: PatternConfig = {
 *   type: 'nonexistent', // ❌ TypeScript error!
 * };
 */
export type PatternType =
${patternNames.map(name => `  | '${name}'`).join('\n')};

/**
 * Array of all pattern type names (for runtime validation)
 */
export const PATTERN_TYPES: PatternType[] = [
${patternNames.map(name => `  '${name}',`).join('\n')}
];

/**
 * Check if a string is a valid pattern type
 */
export function isValidPatternType(type: string): type is PatternType {
  return PATTERN_TYPES.includes(type as PatternType);
}
`;

    fs.writeFileSync(outputPath, tsContent);
    console.log(`Generated ${outputPath}`);
    console.log('Done!');
}

main().catch((error) => {
    console.error('Error:', error);
    process.exit(1);
});
