#!/usr/bin/env node
/**
 * Generate Pattern Types Script
 *
 * Extracts all pattern type names and their props schemas from patterns-registry.json
 * and generates TypeScript types for compile-time validation of render-ui effects.
 *
 * Usage: npx tsx scripts/generate-pattern-types.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface PropSchema {
    required?: boolean;
    types: string[];
    description?: string;
}

interface PatternDefinition {
    type: string;
    category?: string;
    entityAware?: boolean;
    description?: string;
    propsSchema?: Record<string, PropSchema>;
}

interface PatternsRegistry {
    version: string;
    exportedAt: string;
    patterns: Record<string, PatternDefinition>;
}

/**
 * Convert registry type strings to TypeScript types.
 * All props also allow string bindings (e.g., '@entity.x') for runtime resolution.
 */
function mapType(types: string[]): string {
    const tsTypes = types.map(t => {
        switch (t) {
            case 'string': return 'string';
            case 'number': return 'number';
            case 'boolean': return 'boolean';
            case 'array': return 'unknown[]';
            case 'object': return 'Record<string, unknown>';
            case 'function': return '((...args: unknown[]) => unknown)';
            case 'null': return 'null';
            default: return 'unknown';
        }
    });
    // Always allow string bindings (e.g., '@entity.isOpen') for all prop types
    // This is essential for behaviors where values are bound at runtime
    if (!tsTypes.includes('string')) {
        tsTypes.push('string');
    }
    return tsTypes.join(' | ');
}

/**
 * Generate interface for a pattern's props
 */
function generatePropsInterface(patternName: string, propsSchema: Record<string, PropSchema> | undefined): string {
    if (!propsSchema || Object.keys(propsSchema).length === 0) {
        return `  '${patternName}': { patternType: '${patternName}'; };`;
    }

    const props = Object.entries(propsSchema).map(([propName, schema]) => {
        const optional = schema.required ? '' : '?';
        const tsType = mapType(schema.types);
        const comment = schema.description ? `/** ${schema.description} */\n    ` : '';
        return `    ${comment}${propName}${optional}: ${tsType};`;
    });

    return `  '${patternName}': {\n    patternType: '${patternName}';\n${props.join('\n')}\n  };`;
}

async function main() {
    const registryPath = path.join(__dirname, '../src/patterns-registry.json');
    const outputPath = path.join(__dirname, '../src/pattern-types.ts');

    console.log('Reading patterns registry...');
    const registryContent = fs.readFileSync(registryPath, 'utf-8');
    const registry: PatternsRegistry = JSON.parse(registryContent);

    const patternNames = Object.keys(registry.patterns).sort();
    console.log(`Found ${patternNames.length} patterns`);

    // Generate props interfaces for each pattern
    const propsInterfaces = patternNames.map(name =>
        generatePropsInterface(name, registry.patterns[name].propsSchema)
    );

    // Generate TypeScript file
    const tsContent = `/**
 * Pattern Types (Auto-Generated)
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-pattern-types.ts
 * Run: npx tsx scripts/generate-pattern-types.ts
 *
 * Generated: ${new Date().toISOString()}
 * Pattern count: ${patternNames.length}
 */

/**
 * All valid pattern type names from almadar-patterns registry.
 * Use this type in render-ui effects for compile-time validation.
 */
export type PatternType =
${patternNames.map(name => `  | '${name}'`).join('\n')};

/**
 * Pattern props map - each pattern type maps to its valid props interface.
 * This enables full type-checking of pattern configurations.
 */
export interface PatternPropsMap {
${propsInterfaces.join('\n')}
}

/**
 * Get the props type for a specific pattern.
 * 
 * @example
 * type TableProps = PatternProps<'entity-table'>;
 * // { type: 'entity-table'; columns: unknown[]; data?: Record<string, unknown>; ... }
 */
export type PatternProps<T extends PatternType> = PatternPropsMap[T];

/**
 * Type-safe pattern configuration.
 * The props are validated based on the pattern type.
 * 
 * @example
 * // ✅ Valid
 * const config: PatternConfig<'entity-table'> = { 
 *   type: 'entity-table', 
 *   columns: ['name', 'email'] 
 * };
 * 
 * // ❌ Error: Property 'columns' is missing
 * const bad: PatternConfig<'entity-table'> = { type: 'entity-table' };
 */
export type PatternConfig<T extends PatternType = PatternType> = PatternPropsMap[T];

/**
 * Discriminated union of all pattern configs.
 * Use when the pattern type is not known statically.
 */
export type AnyPatternConfig = PatternPropsMap[PatternType];

/**
 * Array of all pattern type names (for runtime validation)
 */
export const PATTERN_TYPES: PatternType[] = [
${patternNames.map(name => `  '${name}',`).join('\n')}
];

/**
 * Check if a string is a valid pattern type
 */
export function isValidPatternType(type: string): type is PatternType {
  return PATTERN_TYPES.includes(type as PatternType);
}
`;

    fs.writeFileSync(outputPath, tsContent);
    console.log(`Generated ${outputPath}`);
    console.log('Done!');
}

main().catch((error) => {
    console.error('Error:', error);
    process.exit(1);
});
