/**
 * Pattern Types (Auto-Generated)
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-pattern-types.ts
 * Run: npx tsx scripts/generate-pattern-types.ts
 *
 * Generated: 2026-02-06T13:19:41.617Z
 * Pattern count: 203
 */

/**
 * All valid pattern type names from almadar-patterns registry.
 * Use this type in render-ui effects for compile-time validation.
 *
 * @example
 * const pattern: PatternConfig = {
 *   type: 'entity-table', // ✅ Valid
 *   entity: 'Task',
 * };
 *
 * const invalid: PatternConfig = {
 *   type: 'nonexistent', // ❌ TypeScript error!
 * };
 */
export type PatternType =
  | 'accordion'
  | 'activation-block'
  | 'admin-dashboard'
  | 'agent-chat-panel'
  | 'ai-analysis-panel'
  | 'alert'
  | 'assessment-form'
  | 'avatar'
  | 'badge'
  | 'bloom-quiz-block'
  | 'board-grid'
  | 'body-measurement-input'
  | 'box'
  | 'breadcrumb'
  | 'button'
  | 'button-group'
  | 'card'
  | 'card-deck'
  | 'card-hand'
  | 'card-selector'
  | 'care-indicator'
  | 'center'
  | 'checkbox'
  | 'checklist'
  | 'checklist-item'
  | 'code-block'
  | 'collision-detector'
  | 'companies-list'
  | 'company-card'
  | 'company-info-card'
  | 'compliance-summary'
  | 'concept-card'
  | 'concept-meta-tags'
  | 'conditional-field'
  | 'confirm-dialog'
  | 'connection-block'
  | 'connections-view'
  | 'container'
  | 'credit-expiration-alert'
  | 'credit-meter'
  | 'custom'
  | 'daily-progress-input'
  | 'dashboard-grid'
  | 'detail-panel'
  | 'dialogue-box'
  | 'divider'
  | 'document-preview'
  | 'drawer'
  | 'drawer-container'
  | 'empty-state'
  | 'entity-cards'
  | 'entity-detail'
  | 'entity-list'
  | 'entity-search'
  | 'entity-table'
  | 'error-state'
  | 'evidence-gallery'
  | 'evidence-thumbnail'
  | 'exercise-video-link'
  | 'filter-group'
  | 'flash-card'
  | 'flash-card-stack'
  | 'flash-cards-display'
  | 'float-button'
  | 'floating-action-menu'
  | 'force-directed-graph'
  | 'form'
  | 'form-fields'
  | 'form-section'
  | 'game-canvas'
  | 'game-controls'
  | 'game-debug-panel'
  | 'game-hud'
  | 'game-menu'
  | 'game-over-screen'
  | 'game-pause-overlay'
  | 'garden-view'
  | 'graph-intelligence'
  | 'graph-legend'
  | 'grid'
  | 'group-session-card'
  | 'growth-meter'
  | 'harvest-card'
  | 'heading'
  | 'hstack'
  | 'icon'
  | 'icon-button'
  | 'image'
  | 'info-display'
  | 'input'
  | 'input-listener'
  | 'inspection-card'
  | 'inspection-checklist'
  | 'inspection-form-demo'
  | 'inspection-process'
  | 'inspection-summary'
  | 'inspection-timeline'
  | 'inspection-wizard'
  | 'inspection-wizard-step'
  | 'inspections-list'
  | 'inspector-card'
  | 'inspectors-list'
  | 'inventory-panel'
  | 'invites-list'
  | 'kinesiology-exam-form'
  | 'label'
  | 'law-reference-badge'
  | 'layer-navigator'
  | 'learning-goal-display'
  | 'level-select'
  | 'lift-tracker'
  | 'link'
  | 'loading-state'
  | 'markdown-content'
  | 'master-detail'
  | 'match3-grid'
  | 'meal-plan-card'
  | 'menu'
  | 'mind-map-canvas'
  | 'mind-map-connections'
  | 'mind-map-header'
  | 'mind-map-node'
  | 'modal'
  | 'modal-container'
  | 'multi-select'
  | 'note-content'
  | 'note-list'
  | 'note-list-item'
  | 'notification'
  | 'nutrition-summary'
  | 'objection-recorder'
  | 'page-header'
  | 'pagination'
  | 'participant-list'
  | 'pattern-proposal'
  | 'phase-indicator'
  | 'photo-attachment'
  | 'plant-card'
  | 'popover'
  | 'progress-bar'
  | 'progress-chart'
  | 'progress-header'
  | 'project-detail'
  | 'projects-list'
  | 'puzzle-board'
  | 'quiz-block'
  | 'radio'
  | 'reflection-block'
  | 'relationship-garden'
  | 'repeatable-form-section'
  | 'rule-check-item'
  | 'runtime-debugger'
  | 'schema-diff-viewer'
  | 'search-bar'
  | 'search-input'
  | 'season-indicator'
  | 'seed-network'
  | 'segment-renderer'
  | 'select'
  | 'session-scheduler'
  | 'shareable-link-generator'
  | 'signature'
  | 'signature-capture'
  | 'simple-grid'
  | 'spacer'
  | 'special-exercise-card'
  | 'spinner'
  | 'split-layout'
  | 'stats'
  | 'stats-grid'
  | 'streaming-display'
  | 'studio-home-web-template'
  | 'studio-project-template'
  | 'suggestions-list'
  | 'switch'
  | 'tab-bar'
  | 'tabbed-layout'
  | 'tabs'
  | 'team-detail'
  | 'team-members-list'
  | 'teams-list'
  | 'text'
  | 'textarea'
  | 'tilemap-renderer'
  | 'title-only'
  | 'todo-list'
  | 'tooltip'
  | 'trainee-card'
  | 'trainee-comparison'
  | 'trust-intelligence'
  | 'trust-meter'
  | 'turn-indicator'
  | 'user-profile'
  | 'users-list'
  | 'violation-form'
  | 'violation-list-item'
  | 'vstack'
  | 'weather-widget'
  | 'weekly-calendar'
  | 'wizard-container'
  | 'wizard-navigation'
  | 'wizard-progress'
  | 'workout-plan-card';

/**
 * Array of all pattern type names (for runtime validation)
 */
export const PATTERN_TYPES: PatternType[] = [
  'accordion',
  'activation-block',
  'admin-dashboard',
  'agent-chat-panel',
  'ai-analysis-panel',
  'alert',
  'assessment-form',
  'avatar',
  'badge',
  'bloom-quiz-block',
  'board-grid',
  'body-measurement-input',
  'box',
  'breadcrumb',
  'button',
  'button-group',
  'card',
  'card-deck',
  'card-hand',
  'card-selector',
  'care-indicator',
  'center',
  'checkbox',
  'checklist',
  'checklist-item',
  'code-block',
  'collision-detector',
  'companies-list',
  'company-card',
  'company-info-card',
  'compliance-summary',
  'concept-card',
  'concept-meta-tags',
  'conditional-field',
  'confirm-dialog',
  'connection-block',
  'connections-view',
  'container',
  'credit-expiration-alert',
  'credit-meter',
  'custom',
  'daily-progress-input',
  'dashboard-grid',
  'detail-panel',
  'dialogue-box',
  'divider',
  'document-preview',
  'drawer',
  'drawer-container',
  'empty-state',
  'entity-cards',
  'entity-detail',
  'entity-list',
  'entity-search',
  'entity-table',
  'error-state',
  'evidence-gallery',
  'evidence-thumbnail',
  'exercise-video-link',
  'filter-group',
  'flash-card',
  'flash-card-stack',
  'flash-cards-display',
  'float-button',
  'floating-action-menu',
  'force-directed-graph',
  'form',
  'form-fields',
  'form-section',
  'game-canvas',
  'game-controls',
  'game-debug-panel',
  'game-hud',
  'game-menu',
  'game-over-screen',
  'game-pause-overlay',
  'garden-view',
  'graph-intelligence',
  'graph-legend',
  'grid',
  'group-session-card',
  'growth-meter',
  'harvest-card',
  'heading',
  'hstack',
  'icon',
  'icon-button',
  'image',
  'info-display',
  'input',
  'input-listener',
  'inspection-card',
  'inspection-checklist',
  'inspection-form-demo',
  'inspection-process',
  'inspection-summary',
  'inspection-timeline',
  'inspection-wizard',
  'inspection-wizard-step',
  'inspections-list',
  'inspector-card',
  'inspectors-list',
  'inventory-panel',
  'invites-list',
  'kinesiology-exam-form',
  'label',
  'law-reference-badge',
  'layer-navigator',
  'learning-goal-display',
  'level-select',
  'lift-tracker',
  'link',
  'loading-state',
  'markdown-content',
  'master-detail',
  'match3-grid',
  'meal-plan-card',
  'menu',
  'mind-map-canvas',
  'mind-map-connections',
  'mind-map-header',
  'mind-map-node',
  'modal',
  'modal-container',
  'multi-select',
  'note-content',
  'note-list',
  'note-list-item',
  'notification',
  'nutrition-summary',
  'objection-recorder',
  'page-header',
  'pagination',
  'participant-list',
  'pattern-proposal',
  'phase-indicator',
  'photo-attachment',
  'plant-card',
  'popover',
  'progress-bar',
  'progress-chart',
  'progress-header',
  'project-detail',
  'projects-list',
  'puzzle-board',
  'quiz-block',
  'radio',
  'reflection-block',
  'relationship-garden',
  'repeatable-form-section',
  'rule-check-item',
  'runtime-debugger',
  'schema-diff-viewer',
  'search-bar',
  'search-input',
  'season-indicator',
  'seed-network',
  'segment-renderer',
  'select',
  'session-scheduler',
  'shareable-link-generator',
  'signature',
  'signature-capture',
  'simple-grid',
  'spacer',
  'special-exercise-card',
  'spinner',
  'split-layout',
  'stats',
  'stats-grid',
  'streaming-display',
  'studio-home-web-template',
  'studio-project-template',
  'suggestions-list',
  'switch',
  'tab-bar',
  'tabbed-layout',
  'tabs',
  'team-detail',
  'team-members-list',
  'teams-list',
  'text',
  'textarea',
  'tilemap-renderer',
  'title-only',
  'todo-list',
  'tooltip',
  'trainee-card',
  'trainee-comparison',
  'trust-intelligence',
  'trust-meter',
  'turn-indicator',
  'user-profile',
  'users-list',
  'violation-form',
  'violation-list-item',
  'vstack',
  'weather-widget',
  'weekly-calendar',
  'wizard-container',
  'wizard-navigation',
  'wizard-progress',
  'workout-plan-card',
];

/**
 * Check if a string is a valid pattern type
 */
export function isValidPatternType(type: string): type is PatternType {
  return PATTERN_TYPES.includes(type as PatternType);
}
